export const UPLOAD_COUNTRIES = "UPLOAD_COUNTRIES";
export const GET_ALL_COUNTRIES = "GET_ALL_COUNTRIES";
export const GET_COUNTRIES_BY = "GET_COUNTRIES_BY";
export const CURRENT_PAGE = "CURRENT_PAGE";
export const GET_COUNTRY_BY = "GET_COUNTRY_BY";
export const FILTER_BY_CONTINENT = "FILTER_BY_CONTINENT";
export const CREATE_ACTIVITY = "CREATE_ACTIVITY";
